version: '2.4'
services:
  caddy:
    container_name: caddy
    image: lucaslorentz/caddy-docker-proxy:latest
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=cloudbuild
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy-data:/data
    restart: unless-stopped
    networks:
      - cloudbuild
    
networks:
  cloudbuild:
    external: true
    name: cloudbuild
volumes:
  caddy-data: